a=100
try:
    a+'100'
except Exception as e:
    print("error :",e)